In [ ]:
import pandas as pd
import numpy as np
import io
import csv

In [ ]:
print(1)

1

In [ ]:
data = """
AGYSUB,LOC,AGELVL,EDLVL,GSEGRD,LOSLVL,OCC,PATCO,PP,PPGRD,SALLVL,STEMOCC,SUPERVIS,TOA,WORKSCH,WORKSTAT,DATECODE,EMPLOYMENT,SALARY,LOS
AA00,11,F,13,,F,0340,2,ES,ES-**,R,XXXX,2,50,F,1,202106,1,181500,18.0
AA00,11,I,15,,H,0905,1,ES,ES-**,R,XXXX,2,50,F,1,202106,1,181500,28.4
AA00,11,E,15,15,E,0905,1,99,GS-15,Q,XXXX,2,30,F,1,202106,1,172500,11.8
AA00,11,D,15,15,D,0905,1,99,GS-15,N,XXXX,8,30,F,1,202106,1,144128,09.8
AA00,11,F,15,13,E,0905,1,99,GS-13,K,XXXX,8,30,F,1,202106,1,114059,12.7
AA00,11,H,15,,E,0301,2,ES,ES-**,S,XXXX,2,50,F,1,202106,1,199300,11.7
AA00,11,E,15,14,D,0905,1,99,GS-14,M,XXXX,8,30,F,1,202106,1,134782,06.8
AA00,11,D,21,14,B,0905,1,99,GS-14,L,XXXX,8,30,F,1,202106,1,126614,02.3
AA00,11,E,21,14,B,0905,1,99,GS-14,M,XXXX,8,30,F,1,202106,1,138866,01.7
AB00,FR,I,13,13,E,1630,2,99,GS-13,H,XXXX,2,10,F,1,202106,1,087415,13.2
AB00,FR,I,13,13,E,1630,2,99,GS-13,H,1320,2,10,F,1,202106,1,087415,13.2
"""

In [ ]:
df = pd.read_csv(io.StringIO(data), dtype={'LOC': str, 'AGELVL': str, 'EDLVL': str, 'OCC': str, 'STEMOCC': str, 'SALARY': np.int64})

# Important columns

- LOC
- AGELVL
- EDLVL
-

In [ ]:
df

   AGYSUB LOC AGELVL EDLVL  ...  DATECODE EMPLOYMENT  SALARY   LOS
0    AA00  11      F    13  ...    202106          1  181500  18.0
1    AA00  11      I    15  ...    202106          1  181500  28.4
2    AA00  11      E    15  ...    202106          1  172500  11.8
3    AA00  11      D    15  ...    202106          1  144128   9.8
4    AA00  11      F    15  ...    202106          1  114059  12.7
5    AA00  11      H    15  ...    202106          1  199300  11.7
6    AA00  11      E    15  ...    202106          1  134782   6.8
7    AA00  11      D    21  ...    202106          1  126614   2.3
8    AA00  11      E    21  ...    202106          1  138866   1.7
9    AB00  FR      I    13  ...    202106          1   87415  13.2
10   AB00  FR      I    13  ...    202106          1   87415  13.2

[11 rows x 20 columns]

In [ ]:
df[df['EMPLOYMENT'] != 1]

Empty DataFrame
Columns: [AGYSUB, LOC, AGELVL, EDLVL, GSEGRD, LOSLVL, OCC, PATCO, PP, PPGRD, SALLVL, STEMOCC, SUPERVIS, TOA, WORKSCH, WORKSTAT, DATECODE, EMPLOYMENT, SALARY, LOS]
Index: []

In [ ]:
df2 = df[['LOC', 'AGELVL', 'EDLVL', 'OCC', 'PATCO', 'SALLVL', 'STEMOCC', 'DATECODE', 'SALARY']]

In [ ]:
loc_dict = {'**': 'UNSPECIFIED',
 '01': 'ALABAMA',
 '02': 'ALASKA',
 '04': 'ARIZONA',
 '05': 'ARKANSAS',
 '06': 'CALIFORNIA',
 '08': 'COLORADO',
 '09': 'CONNECTICUT',
 '10': 'DELAWARE',
 '11': 'DISTRICT OF COLUMBIA',
 '12': 'FLORIDA',
 '13': 'GEORGIA',
 '15': 'HAWAII',
 '16': 'IDAHO',
 '17': 'ILLINOIS',
 '18': 'INDIANA',
 '19': 'IOWA',
 '20': 'KANSAS',
 '21': 'KENTUCKY',
 '22': 'LOUISIANA',
 '23': 'MAINE',
 '24': 'MARYLAND',
 '25': 'MASSACHUSETTS',
 '26': 'MICHIGAN',
 '27': 'MINNESOTA',
 '28': 'MISSISSIPPI',
 '29': 'MISSOURI',
 '30': 'MONTANA',
 '31': 'NEBRASKA',
 '32': 'NEVADA',
 '33': 'NEW HAMPSHIRE',
 '34': 'NEW JERSEY',
 '35': 'NEW MEXICO',
 '36': 'NEW YORK',
 '37': 'NORTH CAROLINA',
 '38': 'NORTH DAKOTA',
 '39': 'OHIO',
 '40': 'OKLAHOMA',
 '41': 'OREGON',
 '42': 'PENNSYLVANIA',
 '44': 'RHODE ISLAND',
 '45': 'SOUTH CAROLINA',
 '46': 'SOUTH DAKOTA',
 '47': 'TENNESSEE',
 '48': 'TEXAS',
 '49': 'UTAH',
 '50': 'VERMONT',
 '51': 'VIRGINIA',
 '53': 'WASHINGTON',
 '54': 'WEST VIRGINIA',
 '55': 'WISCONSIN',
 '56': 'WYOMING',
 'AA': 'ARUBA',
 'AE': 'UNITED ARAB EMIRATES',
 'AF': 'AFGHANISTAN',
 'AG': 'ALGERIA',
 'AJ': 'AZERBAIJAN',
 'AL': 'ALBANIA',
 'AM': 'ARMENIA',
 'AO': 'ANGOLA',
 'AQ': 'AMERICAN SAMOA',
 'AR': 'ARGENTINA',
 'AS': 'AUSTRALIA',
 'AU': 'AUSTRIA',
 'AY': 'ANTARCTICA',
 'BA': 'BAHRAIN',
 'BB': 'BARBADOS',
 'BC': 'BOTSWANA',
 'BD': 'BERMUDA',
 'BE': 'BELGIUM',
 'BF': 'BAHAMAS, THE',
 'BG': 'BANGLADESH',
 'BH': 'BELIZE',
 'BK': 'BOSNIA AND HERZEGOVINA',
 'BM': 'BURMA',
 'BN': 'BENIN',
 'BO': 'BELARUS',
 'BR': 'BRAZIL',
 'BU': 'BULGARIA',
 'BY': 'BURUNDI',
 'CA': 'CANADA',
 'CB': 'CAMBODIA',
 'CD': 'CHAD',
 'CE': 'SRI LANKA',
 'CF': 'CONGO',
 'CG': 'CONGO, DEMOCRATIC REPUBLIC OF THE',
 'CH': 'CHINA',
 'CI': 'CHILE',
 'CM': 'CAMEROON',
 'CN': 'COMOROS',
 'CO': 'COLOMBIA',
 'CQ': 'NORTHERN MARIANA ISLANDS',
 'CS': 'COSTA RICA',
 'CU': 'CUBA',
 'CY': 'CYPRUS',
 'DA': 'DENMARK',
 'DJ': 'DJIBOUTI',
 'DR': 'DOMINICAN REPUBLIC',
 'EC': 'ECUADOR',
 'EG': 'EGYPT',
 'EI': 'IRELAND',
 'EN': 'ESTONIA',
 'ER': 'ERITREA',
 'ES': 'EL SALVADOR',
 'ET': 'ETHIOPIA',
 'EZ': 'CZECH REPUBLIC',
 'FI': 'FINLAND',
 'FJ': 'FIJI',
 'FM': 'MICRONESIA, FEDERATED STATES OF',
 'FR': 'FRANCE',
 'GA': 'GAMBIA, THE',
 'GB': 'GABON',
 'GG': 'GEORGIA',
 'GH': 'GHANA',
 'GM': 'GERMANY',
 'GQ': 'GUAM',
 'GR': 'GREECE',
 'GT': 'GUATEMALA',
 'GV': 'GUINEA',
 'GY': 'GUYANA',
 'HA': 'HAITI',
 'HK': 'HONG KONG',
 'HO': 'HONDURAS',
 'HR': 'CROATIA',
 'HU': 'HUNGARY',
 'IC': 'ICELAND',
 'ID': 'INDONESIA',
 'IN': 'INDIA',
 'IO': 'BRITISH INDIAN OCEAN TERRITORY',
 'IS': 'ISRAEL',
 'IT': 'ITALY',
 'IV': "COTE D'IVOIRE",
 'IZ': 'IRAQ',
 'JA': 'JAPAN',
 'JM': 'JAMAICA',
 'JO': 'JORDAN',
 'KE': 'KENYA',
 'KG': 'KYRGYZSTAN',
 'KS': 'KOREA, REPUBLIC OF',
 'KU': 'KUWAIT',
 'KV': 'KOSOVO',
 'KZ': 'KAZAKHSTAN',
 'LA': 'LAOS',
 'LE': 'LEBANON',
 'LG': 'LATVIA',
 'LH': 'LITHUANIA',
 'LI': 'LIBERIA',
 'LT': 'LESOTHO',
 'LU': 'LUXEMBOURG',
 'LY': 'LIBYA',
 'MA': 'MADAGASCAR',
 'MD': 'MOLDOVA',
 'MG': 'MONGOLIA',
 'MI': 'MALAWI',
 'MJ': 'MONTENEGRO',
 'MK': 'MACEDONIA',
 'ML': 'MALI',
 'MO': 'MOROCCO',
 'MQ': 'MIDWAY ISLANDS',
 'MT': 'MALTA',
 'MU': 'OMAN',
 'MX': 'MEXICO',
 'MY': 'MALAYSIA',
 'MZ': 'MOZAMBIQUE',
 'NG': 'NIGER',
 'NH': 'VANUATU',
 'NI': 'NIGERIA',
 'NL': 'NETHERLANDS',
 'NO': 'NORWAY',
 'NP': 'NEPAL',
 'NT': 'NETHERLANDS ANTILLES',
 'NU': 'NICARAGUA',
 'NZ': 'NEW ZEALAND',
 'PA': 'PARAGUAY',
 'PE': 'PERU',
 'PK': 'PAKISTAN',
 'PL': 'POLAND',
 'PM': 'PANAMA',
 'PO': 'PORTUGAL',
 'PP': 'PAPUA NEW GUINEA',
 'QA': 'QATAR',
 'RI': 'SERBIA',
 'RM': 'MARSHALL ISLANDS',
 'RO': 'ROMANIA',
 'RP': 'PHILIPPINES',
 'RQ': 'PUERTO RICO',
 'RS': 'RUSSIA',
 'RW': 'RWANDA',
 'SA': 'SAUDI ARABIA',
 'SF': 'SOUTH AFRICA',
 'SG': 'SENEGAL',
 'SI': 'SLOVENIA',
 'SL': 'SIERRA LEONE',
 'SN': 'SINGAPORE',
 'SO': 'SOMALIA',
 'SP': 'SPAIN',
 'ST': 'SAINT LUCIA',
 'SU': 'SUDAN',
 'SW': 'SWEDEN',
 'SZ': 'SWITZERLAND',
 'TD': 'TRINIDAD AND TOBAGO',
 'TH': 'THAILAND',
 'TI': 'TAJIKISTAN',
 'TN': 'TONGA',
 'TO': 'TOGO',
 'TP': 'SAO TOME AND PRINCIPE',
 'TS': 'TUNISIA',
 'TT': 'TIMOR',
 'TU': 'TURKEY',
 'TW': 'TAIWAN',
 'TX': 'TURKMENISTAN',
 'TZ': 'TANZANIA',
 'UG': 'UGANDA',
 'UK': 'UNITED KINGDOM',
 'UP': 'UKRAINE',
 'US': 'SUPPRESSED (SEE DATA DEFINITIONS)',
 'UV': 'BURKINA FASO',
 'UY': 'URUGUAY',
 'UZ': 'UZBEKISTAN',
 'VM': 'VIETNAM',
 'VQ': 'VIRGIN ISLANDS',
 'WA': 'NAMIBIA',
 'WS': 'SAMOA',
 'WZ': 'SWAZILAND',
 'YM': 'YEMEN',
 'ZA': 'ZAMBIA',
 'ZI': 'ZIMBABWE'}

In [ ]:
import json
with open('loc_dict.json', 'w') as f:
  f.write(json.dumps(loc_dict))

In [ ]:
df2['LOC'] = df2['LOC'].replace(loc_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df2

                     LOC AGELVL EDLVL   OCC  ...  SALLVL STEMOCC DATECODE  SALARY
0   DISTRICT OF COLUMBIA      F    13  0340  ...       R    XXXX   202106  181500
1   DISTRICT OF COLUMBIA      I    15  0905  ...       R    XXXX   202106  181500
2   DISTRICT OF COLUMBIA      E    15  0905  ...       Q    XXXX   202106  172500
3   DISTRICT OF COLUMBIA      D    15  0905  ...       N    XXXX   202106  144128
4   DISTRICT OF COLUMBIA      F    15  0905  ...       K    XXXX   202106  114059
5   DISTRICT OF COLUMBIA      H    15  0301  ...       S    XXXX   202106  199300
6   DISTRICT OF COLUMBIA      E    15  0905  ...       M    XXXX   202106  134782
7   DISTRICT OF COLUMBIA      D    21  0905  ...       L    XXXX   202106  126614
8   DISTRICT OF COLUMBIA      E    21  0905  ...       M    XXXX   202106  138866
9                 FRANCE      I    13  1630  ...       H    XXXX   202106   87415
10                FRANCE      I    13  1630  ...       H    1320   202106   87415

[11 rows x 9 columns]

In [ ]:
from pprint import pprint
import numpy as np

In [ ]:
agelvl_dict =  {'A': '0-20',
 'B': '20-24',
 'C': '25-29',
 'D': '30-34',
 'E': '35-39',
 'F': '40-44',
 'G': '45-49',
 'H': '50-54',
 'I': '55-59',
 'J': '60-64',
 'K': '65-120',
 'Z': np.nan}

In [ ]:
with open('agelvl_dict.json', 'w') as f:
  f.write(json.dumps(agelvl_dict))

In [ ]:
df2['AGELVL'] = df2['AGELVL'].replace(agelvl_dict)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
edlvl_dict = {'': 'NO EDUCATION LEVEL REPORTED',
 '**': 'UNSPECIFIED',
 '01': 'BELOW HIGH SCHOOL',
 '02': 'BELOW HIGH SCHOOL',
 '03': 'BELOW HIGH SCHOOL',
 '04': 'HIGH SCHOOL OR EQUIVALENCY',
 '05': 'OCCUPATIONAL PROGRAM',
 '06': 'OCCUPATIONAL PROGRAM',
 '07': 'BETWEEN HS & BACHELORS',
 '08': 'BETWEEN HS & BACHELORS',
 '09': 'BETWEEN HS & BACHELORS',
 '10': 'BETWEEN HS & BACHELORS',
 '11': 'BETWEEN HS & BACHELORS',
 '12': 'BETWEEN HS & BACHELORS',
 '13': 'BACHELORS',
 '14': 'POST-BACHELORS',
 '15': 'POST-BACHELORS',
 '16': 'POST-BACHELORS',
 '17': 'MASTERS',
 '18': 'POST MASTERS',
 '19': 'POST MASTERS',
 '20': 'POST MASTERS',
 '21': 'DOCTORATE',
 '22': 'POST-DOCTORATE'}

In [ ]:
with open('edlvl_dict.json', 'w') as f:
  f.write(json.dumps(edlvl_dict))

In [ ]:
df2 = df2[(df2['EDLVL'] != '') & (df2['EDLVL'] != '**')]
df2['EDLVL'] = df2['EDLVL'].replace(edlvl_dict)

In [ ]:
df2

                     LOC AGELVL           EDLVL  ... STEMOCC  DATECODE  SALARY
0   DISTRICT OF COLUMBIA  40-44       BACHELORS  ...    XXXX    202106  181500
1   DISTRICT OF COLUMBIA  55-59  POST-BACHELORS  ...    XXXX    202106  181500
2   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX    202106  172500
3   DISTRICT OF COLUMBIA  30-34  POST-BACHELORS  ...    XXXX    202106  144128
4   DISTRICT OF COLUMBIA  40-44  POST-BACHELORS  ...    XXXX    202106  114059
5   DISTRICT OF COLUMBIA  50-54  POST-BACHELORS  ...    XXXX    202106  199300
6   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX    202106  134782
7   DISTRICT OF COLUMBIA  30-34       DOCTORATE  ...    XXXX    202106  126614
8   DISTRICT OF COLUMBIA  35-39       DOCTORATE  ...    XXXX    202106  138866
9                 FRANCE  55-59       BACHELORS  ...    XXXX    202106   87415
10                FRANCE  55-59       BACHELORS  ...    1320    202106   87415

[11 rows x 9 columns]

In [ ]:
#occ_dict

occ_dict = {'****': 'UNSPECIFIED',
 '0006': 'MISCELLANEOUS OCCUPATIONS',
 '0007': 'MISCELLANEOUS OCCUPATIONS',
 '0017': 'MISCELLANEOUS OCCUPATIONS',
 '0018': 'MISCELLANEOUS OCCUPATIONS',
 '0019': 'MISCELLANEOUS OCCUPATIONS',
 '0020': 'MISCELLANEOUS OCCUPATIONS',
 '0021': 'MISCELLANEOUS OCCUPATIONS',
 '0023': 'MISCELLANEOUS OCCUPATIONS',
 '0025': 'MISCELLANEOUS OCCUPATIONS',
 '0028': 'MISCELLANEOUS OCCUPATIONS',
 '0029': 'MISCELLANEOUS OCCUPATIONS',
 '0030': 'MISCELLANEOUS OCCUPATIONS',
 '0050': 'MISCELLANEOUS OCCUPATIONS',
 '0060': 'MISCELLANEOUS OCCUPATIONS',
 '0062': 'MISCELLANEOUS OCCUPATIONS',
 '0072': 'MISCELLANEOUS OCCUPATIONS',
 '0080': 'MISCELLANEOUS OCCUPATIONS',
 '0081': 'MISCELLANEOUS OCCUPATIONS',
 '0082': 'MISCELLANEOUS OCCUPATIONS',
 '0083': 'MISCELLANEOUS OCCUPATIONS',
 '0084': 'MISCELLANEOUS OCCUPATIONS',
 '0085': 'MISCELLANEOUS OCCUPATIONS',
 '0086': 'MISCELLANEOUS OCCUPATIONS',
 '0089': 'MISCELLANEOUS OCCUPATIONS',
 '0090': 'MISCELLANEOUS OCCUPATIONS',
 '0095': 'MISCELLANEOUS OCCUPATIONS',
 '0099': 'MISCELLANEOUS OCCUPATIONS',
 '0101': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0102': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0105': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0106': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0107': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0110': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0119': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0130': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0131': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0132': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0134': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0135': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0136': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0140': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0142': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0150': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0160': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0170': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0180': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0181': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0184': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0185': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0186': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0187': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0188': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0189': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0190': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0193': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0199': 'SOCIAL SCIENCE, PSYCHOLOGY, AND WELFARE',
 '0201': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0203': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0241': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0244': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0260': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0299': 'PERSONNEL MGMT & INDUSTRIAL  RELATIONS',
 '0301': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0302': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0303': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0304': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0305': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0306': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0308': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0309': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0313': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0318': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0319': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0322': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0326': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0332': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0335': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0340': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0341': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0342': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0343': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0344': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0346': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0350': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0356': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0360': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0361': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0382': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0390': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0391': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0392': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0394': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0399': 'GENERAL ADMIN, CLERICAL, & OFFICE SVCS',
 '0401': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0403': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0404': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0405': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0408': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0410': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0413': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0414': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0415': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0421': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0430': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0434': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0435': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0437': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0440': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0454': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0455': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0457': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0458': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0459': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0460': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0462': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0470': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0471': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0480': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0482': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0485': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0486': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0487': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0499': 'NATURAL RESOURCES MGMT & BIO SCI GROUP',
 '0501': 'ACCOUNTING AND BUDGET',
 '0503': 'ACCOUNTING AND BUDGET',
 '0505': 'ACCOUNTING AND BUDGET',
 '0510': 'ACCOUNTING AND BUDGET',
 '0511': 'ACCOUNTING AND BUDGET',
 '0512': 'ACCOUNTING AND BUDGET',
 '0525': 'ACCOUNTING AND BUDGET',
 '0526': 'ACCOUNTING AND BUDGET',
 '0530': 'ACCOUNTING AND BUDGET',
 '0540': 'ACCOUNTING AND BUDGET',
 '0544': 'ACCOUNTING AND BUDGET',
 '0545': 'ACCOUNTING AND BUDGET',
 '0560': 'ACCOUNTING AND BUDGET',
 '0561': 'ACCOUNTING AND BUDGET',
 '0570': 'ACCOUNTING AND BUDGET',
 '0580': 'ACCOUNTING AND BUDGET',
 '0592': 'ACCOUNTING AND BUDGET',
 '0599': 'ACCOUNTING AND BUDGET',
 '0601': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0602': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0603': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0610': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0620': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0621': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0622': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0630': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0631': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0633': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0635': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0636': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0638': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0640': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0642': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0644': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0645': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0646': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0647': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0648': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0649': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0651': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0660': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0661': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0662': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0665': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0667': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0668': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0669': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0670': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0671': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0672': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0673': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0675': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0679': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0680': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0681': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0682': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0683': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0685': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0688': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0690': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0696': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0698': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0699': 'MEDICAL, HOSPITAL, DENTAL & PUB HEALTH',
 '0701': 'VETERINARY MEDICAL SCIENCE',
 '0704': 'VETERINARY MEDICAL SCIENCE',
 '0799': 'VETERINARY MEDICAL SCIENCE',
 '0801': 'ENGINEERING AND ARCHITECTURE',
 '0802': 'ENGINEERING AND ARCHITECTURE',
 '0803': 'ENGINEERING AND ARCHITECTURE',
 '0804': 'ENGINEERING AND ARCHITECTURE',
 '0806': 'ENGINEERING AND ARCHITECTURE',
 '0807': 'ENGINEERING AND ARCHITECTURE',
 '0808': 'ENGINEERING AND ARCHITECTURE',
 '0809': 'ENGINEERING AND ARCHITECTURE',
 '0810': 'ENGINEERING AND ARCHITECTURE',
 '0817': 'ENGINEERING AND ARCHITECTURE',
 '0819': 'ENGINEERING AND ARCHITECTURE',
 '0828': 'ENGINEERING AND ARCHITECTURE',
 '0830': 'ENGINEERING AND ARCHITECTURE',
 '0840': 'ENGINEERING AND ARCHITECTURE',
 '0850': 'ENGINEERING AND ARCHITECTURE',
 '0854': 'ENGINEERING AND ARCHITECTURE',
 '0855': 'ENGINEERING AND ARCHITECTURE',
 '0856': 'ENGINEERING AND ARCHITECTURE',
 '0858': 'ENGINEERING AND ARCHITECTURE',
 '0861': 'ENGINEERING AND ARCHITECTURE',
 '0871': 'ENGINEERING AND ARCHITECTURE',
 '0873': 'ENGINEERING AND ARCHITECTURE',
 '0880': 'ENGINEERING AND ARCHITECTURE',
 '0881': 'ENGINEERING AND ARCHITECTURE',
 '0890': 'ENGINEERING AND ARCHITECTURE',
 '0893': 'ENGINEERING AND ARCHITECTURE',
 '0895': 'ENGINEERING AND ARCHITECTURE',
 '0896': 'ENGINEERING AND ARCHITECTURE',
 '0899': 'ENGINEERING AND ARCHITECTURE',
 '0901': 'LEGAL AND KINDRED',
 '0904': 'LEGAL AND KINDRED',
 '0905': 'LEGAL AND KINDRED',
 '0930': 'LEGAL AND KINDRED',
 '0935': 'LEGAL AND KINDRED',
 '0950': 'LEGAL AND KINDRED',
 '0958': 'LEGAL AND KINDRED',
 '0962': 'LEGAL AND KINDRED',
 '0963': 'LEGAL AND KINDRED',
 '0965': 'LEGAL AND KINDRED',
 '0967': 'LEGAL AND KINDRED',
 '0986': 'LEGAL AND KINDRED',
 '0987': 'LEGAL AND KINDRED',
 '0991': 'LEGAL AND KINDRED',
 '0993': 'LEGAL AND KINDRED',
 '0996': 'LEGAL AND KINDRED',
 '0998': 'LEGAL AND KINDRED',
 '0999': 'LEGAL AND KINDRED',
 '1001': 'INFORMATION AND ARTS',
 '1008': 'INFORMATION AND ARTS',
 '1010': 'INFORMATION AND ARTS',
 '1015': 'INFORMATION AND ARTS',
 '1016': 'INFORMATION AND ARTS',
 '1020': 'INFORMATION AND ARTS',
 '1021': 'INFORMATION AND ARTS',
 '1035': 'INFORMATION AND ARTS',
 '1040': 'INFORMATION AND ARTS',
 '1046': 'INFORMATION AND ARTS',
 '1051': 'INFORMATION AND ARTS',
 '1054': 'INFORMATION AND ARTS',
 '1056': 'INFORMATION AND ARTS',
 '1060': 'INFORMATION AND ARTS',
 '1071': 'INFORMATION AND ARTS',
 '1082': 'INFORMATION AND ARTS',
 '1083': 'INFORMATION AND ARTS',
 '1084': 'INFORMATION AND ARTS',
 '1087': 'INFORMATION AND ARTS',
 '1099': 'INFORMATION AND ARTS',
 '1101': 'BUSINESS AND INDUSTRY',
 '1102': 'BUSINESS AND INDUSTRY',
 '1103': 'BUSINESS AND INDUSTRY',
 '1104': 'BUSINESS AND INDUSTRY',
 '1105': 'BUSINESS AND INDUSTRY',
 '1106': 'BUSINESS AND INDUSTRY',
 '1107': 'BUSINESS AND INDUSTRY',
 '1109': 'BUSINESS AND INDUSTRY',
 '1130': 'BUSINESS AND INDUSTRY',
 '1140': 'BUSINESS AND INDUSTRY',
 '1144': 'BUSINESS AND INDUSTRY',
 '1145': 'BUSINESS AND INDUSTRY',
 '1146': 'BUSINESS AND INDUSTRY',
 '1147': 'BUSINESS AND INDUSTRY',
 '1150': 'BUSINESS AND INDUSTRY',
 '1152': 'BUSINESS AND INDUSTRY',
 '1160': 'BUSINESS AND INDUSTRY',
 '1163': 'BUSINESS AND INDUSTRY',
 '1165': 'BUSINESS AND INDUSTRY',
 '1169': 'BUSINESS AND INDUSTRY',
 '1170': 'BUSINESS AND INDUSTRY',
 '1171': 'BUSINESS AND INDUSTRY',
 '1173': 'BUSINESS AND INDUSTRY',
 '1176': 'BUSINESS AND INDUSTRY',
 '1199': 'BUSINESS AND INDUSTRY',
 '1202': 'COPYRIGHT, PATENT, AND TRADE',
 '1220': 'COPYRIGHT, PATENT, AND TRADE',
 '1221': 'COPYRIGHT, PATENT, AND TRADE',
 '1222': 'COPYRIGHT, PATENT, AND TRADE',
 '1223': 'COPYRIGHT, PATENT, AND TRADE',
 '1224': 'COPYRIGHT, PATENT, AND TRADE',
 '1226': 'COPYRIGHT, PATENT, AND TRADE',
 '1301': 'PHYSICAL SCIENCES',
 '1306': 'PHYSICAL SCIENCES',
 '1310': 'PHYSICAL SCIENCES',
 '1311': 'PHYSICAL SCIENCES',
 '1313': 'PHYSICAL SCIENCES',
 '1315': 'PHYSICAL SCIENCES',
 '1316': 'PHYSICAL SCIENCES',
 '1320': 'PHYSICAL SCIENCES',
 '1321': 'PHYSICAL SCIENCES',
 '1330': 'PHYSICAL SCIENCES',
 '1340': 'PHYSICAL SCIENCES',
 '1341': 'PHYSICAL SCIENCES',
 '1350': 'PHYSICAL SCIENCES',
 '1360': 'PHYSICAL SCIENCES',
 '1361': 'PHYSICAL SCIENCES',
 '1370': 'PHYSICAL SCIENCES',
 '1371': 'PHYSICAL SCIENCES',
 '1372': 'PHYSICAL SCIENCES',
 '1373': 'PHYSICAL SCIENCES',
 '1374': 'PHYSICAL SCIENCES',
 '1380': 'PHYSICAL SCIENCES',
 '1382': 'PHYSICAL SCIENCES',
 '1384': 'PHYSICAL SCIENCES',
 '1397': 'PHYSICAL SCIENCES',
 '1399': 'PHYSICAL SCIENCES',
 '1410': 'LIBRARY AND ARCHIVES',
 '1411': 'LIBRARY AND ARCHIVES',
 '1412': 'LIBRARY AND ARCHIVES',
 '1420': 'LIBRARY AND ARCHIVES',
 '1421': 'LIBRARY AND ARCHIVES',
 '1499': 'LIBRARY AND ARCHIVES',
 '1501': 'MATHEMATICS AND STATISTICS',
 '1510': 'MATHEMATICS AND STATISTICS',
 '1515': 'MATHEMATICS AND STATISTICS',
 '1520': 'MATHEMATICS AND STATISTICS',
 '1521': 'MATHEMATICS AND STATISTICS',
 '1529': 'MATHEMATICS AND STATISTICS',
 '1530': 'MATHEMATICS AND STATISTICS',
 '1531': 'MATHEMATICS AND STATISTICS',
 '1541': 'MATHEMATICS AND STATISTICS',
 '1550': 'MATHEMATICS AND STATISTICS',
 '1599': 'MATHEMATICS AND STATISTICS',
 '1601': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1603': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1630': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1640': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1654': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1658': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1667': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1670': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1699': 'EQUIPMENT, FACILITIES, AND SERVICES',
 '1701': 'EDUCATION',
 '1702': 'EDUCATION',
 '1710': 'EDUCATION',
 '1712': 'EDUCATION',
 '1715': 'EDUCATION',
 '1720': 'EDUCATION',
 '1725': 'EDUCATION',
 '1730': 'EDUCATION',
 '1740': 'EDUCATION',
 '1750': 'EDUCATION',
 '1799': 'EDUCATION',
 '1801': 'INVESTIGATION',
 '1802': 'INVESTIGATION',
 '1805': 'INVESTIGATION',
 '1810': 'INVESTIGATION',
 '1811': 'INVESTIGATION',
 '1815': 'INVESTIGATION',
 '1822': 'INVESTIGATION',
 '1825': 'INVESTIGATION',
 '1831': 'INVESTIGATION',
 '1849': 'INVESTIGATION',
 '1850': 'INVESTIGATION',
 '1860': 'INVESTIGATION',
 '1862': 'INVESTIGATION',
 '1863': 'INVESTIGATION',
 '1881': 'INVESTIGATION',
 '1889': 'INVESTIGATION',
 '1894': 'INVESTIGATION',
 '1895': 'INVESTIGATION',
 '1896': 'INVESTIGATION',
 '1899': 'INVESTIGATION',
 '1910': 'QUALITY ASSURANCE, INSPECTION, & GRADING',
 '1980': 'QUALITY ASSURANCE, INSPECTION, & GRADING',
 '1981': 'QUALITY ASSURANCE, INSPECTION, & GRADING',
 '1999': 'QUALITY ASSURANCE, INSPECTION, & GRADING',
 '2001': 'SUPPLY',
 '2003': 'SUPPLY',
 '2005': 'SUPPLY',
 '2010': 'SUPPLY',
 '2030': 'SUPPLY',
 '2032': 'SUPPLY',
 '2091': 'SUPPLY',
 '2099': 'SUPPLY',
 '2101': 'TRANSPORTATION',
 '2102': 'TRANSPORTATION',
 '2110': 'TRANSPORTATION',
 '2121': 'TRANSPORTATION',
 '2123': 'TRANSPORTATION',
 '2125': 'TRANSPORTATION',
 '2130': 'TRANSPORTATION',
 '2131': 'TRANSPORTATION',
 '2135': 'TRANSPORTATION',
 '2144': 'TRANSPORTATION',
 '2150': 'TRANSPORTATION',
 '2151': 'TRANSPORTATION',
 '2152': 'TRANSPORTATION',
 '2154': 'TRANSPORTATION',
 '2161': 'TRANSPORTATION',
 '2181': 'TRANSPORTATION',
 '2183': 'TRANSPORTATION',
 '2185': 'TRANSPORTATION',
 '2186': 'TRANSPORTATION',
 '2199': 'TRANSPORTATION',
 '2210': 'INFORMATION TECHNOLOGY',
 '2299': 'INFORMATION TECHNOLOGY',
 '2501': 'WIRE COMM. EQUIP. INSTALLTN & MAINTNCE',
 '2502': 'WIRE COMM. EQUIP. INSTALLTN & MAINTNCE',
 '2504': 'WIRE COMM. EQUIP. INSTALLTN & MAINTNCE',
 '2601': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2602': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2604': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2606': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2608': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2610': 'ELECTRONIC EQUIP. INSTALLTN & MAINTNCE',
 '2801': 'ELECTRICAL INSTALLATION AND MAINTENANCE',
 '2805': 'ELECTRICAL INSTALLATION AND MAINTENANCE',
 '2810': 'ELECTRICAL INSTALLATION AND MAINTENANCE',
 '2854': 'ELECTRICAL INSTALLATION AND MAINTENANCE',
 '2892': 'ELECTRICAL INSTALLATION AND MAINTENANCE',
 '3101': 'FABRIC AND LEATHER WORK',
 '3105': 'FABRIC AND LEATHER WORK',
 '3106': 'FABRIC AND LEATHER WORK',
 '3111': 'FABRIC AND LEATHER WORK',
 '3301': 'INSTRUMENT WORK',
 '3306': 'INSTRUMENT WORK',
 '3314': 'INSTRUMENT WORK',
 '3359': 'INSTRUMENT WORK',
 '3378': 'INSTRUMENT WORK',
 '3401': 'MACHINE TOOL WORK',
 '3414': 'MACHINE TOOL WORK',
 '3416': 'MACHINE TOOL WORK',
 '3428': 'MACHINE TOOL WORK',
 '3501': 'GENERAL SERVICES AND SUPPORT WORK',
 '3502': 'GENERAL SERVICES AND SUPPORT WORK',
 '3511': 'GENERAL SERVICES AND SUPPORT WORK',
 '3513': 'GENERAL SERVICES AND SUPPORT WORK',
 '3515': 'GENERAL SERVICES AND SUPPORT WORK',
 '3546': 'GENERAL SERVICES AND SUPPORT WORK',
 '3566': 'GENERAL SERVICES AND SUPPORT WORK',
 '3601': 'STRUCTURAL AND FINISHING WORK',
 '3602': 'STRUCTURAL AND FINISHING WORK',
 '3603': 'STRUCTURAL AND FINISHING WORK',
 '3604': 'STRUCTURAL AND FINISHING WORK',
 '3605': 'STRUCTURAL AND FINISHING WORK',
 '3606': 'STRUCTURAL AND FINISHING WORK',
 '3610': 'STRUCTURAL AND FINISHING WORK',
 '3701': 'METAL PROCESSING',
 '3703': 'METAL PROCESSING',
 '3705': 'METAL PROCESSING',
 '3707': 'METAL PROCESSING',
 '3711': 'METAL PROCESSING',
 '3712': 'METAL PROCESSING',
 '3725': 'METAL PROCESSING',
 '3727': 'METAL PROCESSING',
 '3769': 'METAL PROCESSING',
 '3801': 'METAL WORK',
 '3802': 'METAL WORK',
 '3806': 'METAL WORK',
 '3808': 'METAL WORK',
 '3809': 'METAL WORK',
 '3820': 'METAL WORK',
 '3869': 'METAL WORK',
 '3901': 'MOVIE, RADIO, TV & SOUND EQUIP OPERATING',
 '3910': 'MOVIE, RADIO, TV & SOUND EQUIP OPERATING',
 '3940': 'MOVIE, RADIO, TV & SOUND EQUIP OPERATING',
 '4010': 'LENS AND CRYSTAL WORK',
 '4101': 'PAINTING AND PAPERHANGING',
 '4102': 'PAINTING AND PAPERHANGING',
 '4104': 'PAINTING AND PAPERHANGING',
 '4201': 'PLUMBING AND PIPEFITTING',
 '4204': 'PLUMBING AND PIPEFITTING',
 '4206': 'PLUMBING AND PIPEFITTING',
 '4255': 'PLUMBING AND PIPEFITTING',
 '4301': 'PLIABLE MATERIALS WORK',
 '4352': 'PLIABLE MATERIALS WORK',
 '4361': 'PLIABLE MATERIALS WORK',
 '4373': 'PLIABLE MATERIALS WORK',
 '4401': 'PRINTING',
 '4402': 'PRINTING',
 '4403': 'PRINTING',
 '4406': 'PRINTING',
 '4416': 'PRINTING',
 '4417': 'PRINTING',
 '4441': 'PRINTING',
 '4449': 'PRINTING',
 '4454': 'PRINTING',
 '4601': 'WOOD WORK',
 '4602': 'WOOD WORK',
 '4604': 'WOOD WORK',
 '4605': 'WOOD WORK',
 '4607': 'WOOD WORK',
 '4616': 'WOOD WORK',
 '4701': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4714': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4715': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4717': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4737': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4741': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4742': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4745': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4749': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4754': 'GENERAL MAINTENANCE AND OPERATIONS WORK',
 '4801': 'GENERAL EQUIPMENT MAINTENANCE',
 '4804': 'GENERAL EQUIPMENT MAINTENANCE',
 '4805': 'GENERAL EQUIPMENT MAINTENANCE',
 '4807': 'GENERAL EQUIPMENT MAINTENANCE',
 '4816': 'GENERAL EQUIPMENT MAINTENANCE',
 '4818': 'GENERAL EQUIPMENT MAINTENANCE',
 '4819': 'GENERAL EQUIPMENT MAINTENANCE',
 '4840': 'GENERAL EQUIPMENT MAINTENANCE',
 '4850': 'GENERAL EQUIPMENT MAINTENANCE',
 '4855': 'GENERAL EQUIPMENT MAINTENANCE',
 '5001': 'PLANT AND ANIMAL WORK',
 '5002': 'PLANT AND ANIMAL WORK',
 '5003': 'PLANT AND ANIMAL WORK',
 '5026': 'PLANT AND ANIMAL WORK',
 '5031': 'PLANT AND ANIMAL WORK',
 '5042': 'PLANT AND ANIMAL WORK',
 '5048': 'PLANT AND ANIMAL WORK',
 '5201': 'MISCELLANEOUS OCCUPATIONS',
 '5205': 'MISCELLANEOUS OCCUPATIONS',
 '5210': 'MISCELLANEOUS OCCUPATIONS',
 '5220': 'MISCELLANEOUS OCCUPATIONS',
 '5221': 'MISCELLANEOUS OCCUPATIONS',
 '5301': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5306': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5309': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5310': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5313': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5317': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5318': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5323': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5334': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5350': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5352': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5378': 'INDUSTRIAL EQUIPMENT MAINTENANCE',
 '5401': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5402': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5406': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5407': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5408': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5409': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5413': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5415': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5419': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5423': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5426': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5440': 'INDUSTRIAL EQUIPMENT OPERATION',
 '5701': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5703': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5704': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5705': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5716': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5725': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5729': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5736': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5737': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5738': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5767': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5782': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5784': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5786': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5788': 'TRANSPORT/MOBILE EQUIPMENT OPERATION',
 '5801': 'TRANSPORT/MOBILE EQUIPMENT MAINTENANCE',
 '5803': 'TRANSPORT/MOBILE EQUIPMENT MAINTENANCE',
 '5806': 'TRANSPORT/MOBILE EQUIPMENT MAINTENANCE',
 '5823': 'TRANSPORT/MOBILE EQUIPMENT MAINTENANCE',
 '5876': 'TRANSPORT/MOBILE EQUIPMENT MAINTENANCE',
 '6501': 'AMMO, EXPLOSIVES, &TOXIC MATERIALS WORK',
 '6502': 'AMMO, EXPLOSIVES, &TOXIC MATERIALS WORK',
 '6505': 'AMMO, EXPLOSIVES, &TOXIC MATERIALS WORK',
 '6511': 'AMMO, EXPLOSIVES, &TOXIC MATERIALS WORK',
 '6601': 'ARMAMENT WORK',
 '6605': 'ARMAMENT WORK',
 '6610': 'ARMAMENT WORK',
 '6641': 'ARMAMENT WORK',
 '6652': 'ARMAMENT WORK',
 '6656': 'ARMAMENT WORK',
 '6901': 'WAREHOUSING AND STOCK HANDLING',
 '6904': 'WAREHOUSING AND STOCK HANDLING',
 '6907': 'WAREHOUSING AND STOCK HANDLING',
 '6910': 'WAREHOUSING AND STOCK HANDLING',
 '6912': 'WAREHOUSING AND STOCK HANDLING',
 '6913': 'WAREHOUSING AND STOCK HANDLING',
 '6914': 'WAREHOUSING AND STOCK HANDLING',
 '6941': 'WAREHOUSING AND STOCK HANDLING',
 '6968': 'WAREHOUSING AND STOCK HANDLING',
 '7001': 'PACKING AND PROCESSING',
 '7002': 'PACKING AND PROCESSING',
 '7006': 'PACKING AND PROCESSING',
 '7009': 'PACKING AND PROCESSING',
 '7301': 'LAUNDRY, DRY CLEANING, AND PRESSING',
 '7304': 'LAUNDRY, DRY CLEANING, AND PRESSING',
 '7305': 'LAUNDRY, DRY CLEANING, AND PRESSING',
 '7401': 'FOOD PREPARATION AND SERVING',
 '7402': 'FOOD PREPARATION AND SERVING',
 '7404': 'FOOD PREPARATION AND SERVING',
 '7407': 'FOOD PREPARATION AND SERVING',
 '7408': 'FOOD PREPARATION AND SERVING',
 '7420': 'FOOD PREPARATION AND SERVING',
 '7601': 'PERSONAL SERVICES',
 '7603': 'PERSONAL SERVICES',
 '8201': 'FLUID SYSTEMS MAINTENANCE',
 '8255': 'FLUID SYSTEMS MAINTENANCE',
 '8268': 'FLUID SYSTEMS MAINTENANCE',
 '8601': 'ENGINE OVERHAUL',
 '8602': 'ENGINE OVERHAUL',
 '8610': 'ENGINE OVERHAUL',
 '8801': 'AIRCRAFT OVERHAUL',
 '8810': 'AIRCRAFT OVERHAUL',
 '8840': 'AIRCRAFT OVERHAUL',
 '8852': 'AIRCRAFT OVERHAUL',
 '8862': 'AIRCRAFT OVERHAUL',
 '9901': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9902': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9903': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9904': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9905': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9906': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9907': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9908': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9914': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9915': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9916': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9917': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9918': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9919': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9920': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9921': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9923': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9924': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9925': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9927': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9928': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9929': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9930': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9931': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9932': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9933': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9934': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9936': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9939': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9940': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9942': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9944': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9945': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9952': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9954': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9955': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9957': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9960': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9961': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9965': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9968': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9971': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9972': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9973': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9975': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9976': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9982': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9985': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9988': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9991': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9993': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9994': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9995': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9996': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9997': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9998': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS',
 '9999': 'VESSEL JOBS EXCLUDED FROM FED WAGE SYS'}

In [ ]:
with open('occ_dict.json', 'w') as f:
  f.write(json.dumps(occ_dict))

In [ ]:
df2['OCC'] = df2['OCC'].replace(occ_dict)

In [ ]:
df2

                     LOC AGELVL           EDLVL  ... STEMOCC  DATECODE  SALARY
0   DISTRICT OF COLUMBIA  40-44       BACHELORS  ...    XXXX    202106  181500
1   DISTRICT OF COLUMBIA  55-59  POST-BACHELORS  ...    XXXX    202106  181500
2   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX    202106  172500
3   DISTRICT OF COLUMBIA  30-34  POST-BACHELORS  ...    XXXX    202106  144128
4   DISTRICT OF COLUMBIA  40-44  POST-BACHELORS  ...    XXXX    202106  114059
5   DISTRICT OF COLUMBIA  50-54  POST-BACHELORS  ...    XXXX    202106  199300
6   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX    202106  134782
7   DISTRICT OF COLUMBIA  30-34       DOCTORATE  ...    XXXX    202106  126614
8   DISTRICT OF COLUMBIA  35-39       DOCTORATE  ...    XXXX    202106  138866
9                 FRANCE  55-59       BACHELORS  ...    XXXX    202106   87415
10                FRANCE  55-59       BACHELORS  ...    1320    202106   87415

[11 rows x 9 columns]

In [ ]:
patco_dict = {1: 'Professional',
 2: 'Administrative',
 3: 'Technical',
 4: 'Clerical',
 5: 'Other White Collar',
 6: 'Blue Collar',
 9: np.nan}

In [ ]:
with open('patco_dict.json', 'w') as f:
  f.write(json.dumps(patco_dict))

In [ ]:
df2['PATCO'] = df2['PATCO'].replace(patco_dict)

In [ ]:
df2

                     LOC AGELVL           EDLVL  ... STEMOCC DATECODE  SALARY
0   DISTRICT OF COLUMBIA  40-44       BACHELORS  ...    XXXX   202106  181500
1   DISTRICT OF COLUMBIA  55-59  POST-BACHELORS  ...    XXXX   202106  181500
2   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX   202106  172500
3   DISTRICT OF COLUMBIA  30-34  POST-BACHELORS  ...    XXXX   202106  144128
4   DISTRICT OF COLUMBIA  40-44  POST-BACHELORS  ...    XXXX   202106  114059
5   DISTRICT OF COLUMBIA  50-54  POST-BACHELORS  ...    XXXX   202106  199300
6   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX   202106  134782
7   DISTRICT OF COLUMBIA  30-34       DOCTORATE  ...    XXXX   202106  126614
8   DISTRICT OF COLUMBIA  35-39       DOCTORATE  ...    XXXX   202106  138866
9                 FRANCE  55-59       BACHELORS  ...    XXXX   202106   87415
10                FRANCE  55-59       BACHELORS  ...    1320   202106   87415

[11 rows x 9 columns]

In [ ]:
sallvl_dict = {'A': 'Less than $20,000',
 'B': '$20,000 - $29,999',
 'C': '$30,000 - $39,999',
 'D': '$40,000 - $49,999',
 'E': '$50,000 - $59,999',
 'F': '$60,000 - $69,999',
 'G': '$70,000 - $79,999',
 'H': '$80,000 - $89,999',
 'I': '$90,000 - $99,999',
 'J': '$100,000 - $109,999',
 'K': '$110,000 - $119,999',
 'L': '$120,000 - $129,999',
 'M': '$130,000 - $139,999',
 'N': '$140,000 - $149,999',
 'O': '$150,000 - $159,999',
 'P': '$160,000 - $169,999',
 'Q': '$170,000 - $179,999',
 'R': '$180,000 - $189,999',
 'S': '$190,000 - $199,999',
 'T': '$200,000 - $219,999',
 'U': '$220,000 - $239,999',
 'V': '$240,000 - $259,999',
 'W': '$260,000 - $279,999',
 'X': '$280,000 - $299,999',
 'Y': '$300,000 or more',
 'Z': 'Unspecified or Zero'}

In [ ]:
with open('sallvl_dict.json', 'w') as f:
  f.write(json.dumps(sallvl_dict))

In [ ]:
df2 = df2[df2['SALLVL'] != 'Z']

df2['SALLVL'] = df2['SALLVL'].replace(sallvl_dict)

In [ ]:
df2

                     LOC AGELVL           EDLVL  ... STEMOCC DATECODE  SALARY
0   DISTRICT OF COLUMBIA  40-44       BACHELORS  ...    XXXX   202106  181500
1   DISTRICT OF COLUMBIA  55-59  POST-BACHELORS  ...    XXXX   202106  181500
2   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX   202106  172500
3   DISTRICT OF COLUMBIA  30-34  POST-BACHELORS  ...    XXXX   202106  144128
4   DISTRICT OF COLUMBIA  40-44  POST-BACHELORS  ...    XXXX   202106  114059
5   DISTRICT OF COLUMBIA  50-54  POST-BACHELORS  ...    XXXX   202106  199300
6   DISTRICT OF COLUMBIA  35-39  POST-BACHELORS  ...    XXXX   202106  134782
7   DISTRICT OF COLUMBIA  30-34       DOCTORATE  ...    XXXX   202106  126614
8   DISTRICT OF COLUMBIA  35-39       DOCTORATE  ...    XXXX   202106  138866
9                 FRANCE  55-59       BACHELORS  ...    XXXX   202106   87415
10                FRANCE  55-59       BACHELORS  ...    1320   202106   87415

[11 rows x 9 columns]

In [ ]:
stemocc_dict = {'****': ('UNSPECIFIED', 'UNSPECIFIED'),
 '0020': ('SCIENCE OCCUPATIONS', 'COMMUNITY PLANNING'),
 '0028': ('SCIENCE OCCUPATIONS', 'ENVIRONMENTAL PROTECTION SPECIALIST'),
 '0072': ('SCIENCE OCCUPATIONS', 'FINGERPRINT IDENTIFICATION'),
 '0101': ('SCIENCE OCCUPATIONS', 'SOCIAL SCIENCE'),
 '0110': ('SCIENCE OCCUPATIONS', 'ECONOMIST'),
 '0130': ('SCIENCE OCCUPATIONS', 'FOREIGN AFFAIRS'),
 '0131': ('SCIENCE OCCUPATIONS', 'INTERNATIONAL RELATIONS'),
 '0132': ('SCIENCE OCCUPATIONS', 'INTELLIGENCE'),
 '0136': ('SCIENCE OCCUPATIONS', 'INTERNATIONAL COOPERATION'),
 '0140': ('SCIENCE OCCUPATIONS', 'WORKFORCE RESEARCH AND ANALYSIS'),
 '0150': ('SCIENCE OCCUPATIONS', 'GEOGRAPHY'),
 '0160': ('SCIENCE OCCUPATIONS', 'CIVIL RIGHTS ANALYSIS'),
 '0180': ('SCIENCE OCCUPATIONS', 'PSYCHOLOGY'),
 '0184': ('SCIENCE OCCUPATIONS', 'SOCIOLOGY'),
 '0190': ('SCIENCE OCCUPATIONS', 'GENERAL ANTHROPOLOGY'),
 '0193': ('SCIENCE OCCUPATIONS', 'ARCHEOLOGY'),
 '0401': ('SCIENCE OCCUPATIONS',
          'GENERAL NATURAL RESOURCES MANAGEMENT AND BIOLOGICAL SCIENCES'),
 '0403': ('SCIENCE OCCUPATIONS', 'MICROBIOLOGY'),
 '0405': ('SCIENCE OCCUPATIONS', 'PHARMACOLOGY'),
 '0408': ('SCIENCE OCCUPATIONS', 'ECOLOGY'),
 '0410': ('SCIENCE OCCUPATIONS', 'ZOOLOGY'),
 '0413': ('SCIENCE OCCUPATIONS', 'PHYSIOLOGY'),
 '0414': ('SCIENCE OCCUPATIONS', 'ENTOMOLOGY'),
 '0415': ('SCIENCE OCCUPATIONS', 'TOXICOLOGY'),
 '0430': ('SCIENCE OCCUPATIONS', 'BOTANY'),
 '0434': ('SCIENCE OCCUPATIONS', 'PLANT PATHOLOGY'),
 '0435': ('SCIENCE OCCUPATIONS', 'PLANT PHYSIOLOGY'),
 '0437': ('SCIENCE OCCUPATIONS', 'HORTICULTURE'),
 '0440': ('SCIENCE OCCUPATIONS', 'GENETICS'),
 '0454': ('SCIENCE OCCUPATIONS', 'RANGELAND MANAGEMENT'),
 '0457': ('SCIENCE OCCUPATIONS', 'SOIL CONSERVATION'),
 '0460': ('SCIENCE OCCUPATIONS', 'FORESTRY'),
 '0470': ('SCIENCE OCCUPATIONS', 'SOIL SCIENCE'),
 '0471': ('SCIENCE OCCUPATIONS', 'AGRONOMY'),
 '0480': ('SCIENCE OCCUPATIONS', 'FISH AND WILDLIFE ADMINISTRATION'),
 '0482': ('SCIENCE OCCUPATIONS', 'FISH BIOLOGY'),
 '0485': ('SCIENCE OCCUPATIONS', 'WILDLIFE REFUGE MANAGEMENT'),
 '0486': ('SCIENCE OCCUPATIONS', 'WILDLIFE BIOLOGY'),
 '0487': ('SCIENCE OCCUPATIONS', 'ANIMAL SCIENCE'),
 '0601': ('HEALTH OCCUPATIONS', 'GENERAL HEALTH SCIENCE'),
 '0602': ('HEALTH OCCUPATIONS', 'MEDICAL OFFICER'),
 '0610': ('HEALTH OCCUPATIONS', 'NURSE'),
 '0620': ('HEALTH OCCUPATIONS', 'PRACTICAL NURSE'),
 '0630': ('HEALTH OCCUPATIONS', 'DIETITIAN AND NUTRITIONIST'),
 '0631': ('HEALTH OCCUPATIONS', 'OCCUPATIONAL THERAPIST'),
 '0633': ('HEALTH OCCUPATIONS', 'PHYSICAL THERAPIST'),
 '0635': ('HEALTH OCCUPATIONS', 'KINESIOTHERAPY'),
 '0638': ('HEALTH OCCUPATIONS', 'RECREATION/CREATIVE ARTS THERAPIST'),
 '0651': ('HEALTH OCCUPATIONS', 'RESPIRATORY THERAPIST'),
 '0660': ('HEALTH OCCUPATIONS', 'PHARMACIST'),
 '0662': ('HEALTH OCCUPATIONS', 'OPTOMETRIST'),
 '0665': ('HEALTH OCCUPATIONS', 'SPEECH PATHOLOGY AND AUDIOLOGY'),
 '0667': ('HEALTH OCCUPATIONS', 'ORTHOTIST AND PROSTHETIST'),
 '0668': ('HEALTH OCCUPATIONS', 'PODIATRIST'),
 '0670': ('HEALTH OCCUPATIONS', 'HEALTH SYSTEM ADMINISTRATION'),
 '0682': ('HEALTH OCCUPATIONS', 'DENTAL HYGIENE'),
 '0685': ('HEALTH OCCUPATIONS', 'PUBLIC HEALTH PROGRAM SPECIALIST'),
 '0690': ('HEALTH OCCUPATIONS', 'INDUSTRIAL HYGIENE'),
 '0696': ('HEALTH OCCUPATIONS', 'CONSUMER SAFETY'),
 '0801': ('ENGINEERING OCCUPATIONS', 'GENERAL ENGINEERING'),
 '0803': ('ENGINEERING OCCUPATIONS', 'SAFETY ENGINEERING'),
 '0804': ('ENGINEERING OCCUPATIONS', 'FIRE PROTECTION ENGINEERING'),
 '0806': ('ENGINEERING OCCUPATIONS', 'MATERIALS ENGINEERING'),
 '0807': ('ENGINEERING OCCUPATIONS', 'LANDSCAPE ARCHITECTURE'),
 '0808': ('ENGINEERING OCCUPATIONS', 'ARCHITECTURE'),
 '0810': ('ENGINEERING OCCUPATIONS', 'CIVIL ENGINEERING'),
 '0819': ('ENGINEERING OCCUPATIONS', 'ENVIRONMENTAL ENGINEERING'),
 '0828': ('ENGINEERING OCCUPATIONS', 'CONSTRUCTION ANALYST'),
 '0830': ('ENGINEERING OCCUPATIONS', 'MECHANICAL ENGINEERING'),
 '0840': ('ENGINEERING OCCUPATIONS', 'NUCLEAR ENGINEERING'),
 '0850': ('ENGINEERING OCCUPATIONS', 'ELECTRICAL ENGINEERING'),
 '0854': ('ENGINEERING OCCUPATIONS', 'COMPUTER ENGINEERING'),
 '0855': ('ENGINEERING OCCUPATIONS', 'ELECTRONICS ENGINEERING'),
 '0858': ('ENGINEERING OCCUPATIONS', 'BIOENGINEERING & BIOMEDICAL ENGINEERING'),
 '0861': ('ENGINEERING OCCUPATIONS', 'AEROSPACE ENGINEERING'),
 '0871': ('ENGINEERING OCCUPATIONS', 'NAVAL ARCHITECTURE'),
 '0880': ('ENGINEERING OCCUPATIONS', 'MINING ENGINEERING'),
 '0881': ('ENGINEERING OCCUPATIONS', 'PETROLEUM ENGINEERING'),
 '0890': ('ENGINEERING OCCUPATIONS', 'AGRICULTURAL ENGINEERING'),
 '0893': ('ENGINEERING OCCUPATIONS', 'CHEMICAL ENGINEERING'),
 '0896': ('ENGINEERING OCCUPATIONS', 'INDUSTRIAL ENGINEERING'),
 '1021': ('ENGINEERING OCCUPATIONS', 'OFFICE DRAFTING'),
 '1301': ('SCIENCE OCCUPATIONS', 'GENERAL PHYSICAL SCIENCE'),
 '1306': ('SCIENCE OCCUPATIONS', 'HEALTH PHYSICS'),
 '1310': ('SCIENCE OCCUPATIONS', 'PHYSICS'),
 '1313': ('SCIENCE OCCUPATIONS', 'GEOPHYSICS'),
 '1315': ('SCIENCE OCCUPATIONS', 'HYDROLOGY'),
 '1320': ('SCIENCE OCCUPATIONS', 'CHEMISTRY'),
 '1321': ('SCIENCE OCCUPATIONS', 'METALLURGY'),
 '1330': ('SCIENCE OCCUPATIONS', 'ASTRONOMY AND SPACE SCIENCE'),
 '1340': ('SCIENCE OCCUPATIONS', 'METEOROLOGY'),
 '1350': ('SCIENCE OCCUPATIONS', 'GEOLOGY'),
 '1360': ('SCIENCE OCCUPATIONS', 'OCEANOGRAPHY'),
 '1361': ('SCIENCE OCCUPATIONS', 'NAVIGATIONAL INFORMATION'),
 '1370': ('SCIENCE OCCUPATIONS', 'CARTOGRAPHY'),
 '1372': ('SCIENCE OCCUPATIONS', 'GEODESY'),
 '1373': ('SCIENCE OCCUPATIONS', 'LAND SURVEYING'),
 '1380': ('SCIENCE OCCUPATIONS', 'FOREST PRODUCTS TECHNOLOGY'),
 '1382': ('SCIENCE OCCUPATIONS', 'FOOD TECHNOLOGY'),
 '1384': ('SCIENCE OCCUPATIONS', 'TEXTILE TECHNOLOGY'),
 '1397': ('SCIENCE OCCUPATIONS', 'DOCUMENT ANALYSIS'),
 '1501': ('MATHEMATICS OCCUPATIONS', 'GENERAL MATHEMATICS AND STATISTICS'),
 '1510': ('MATHEMATICS OCCUPATIONS', 'ACTUARIAL SCIENCE'),
 '1515': ('MATHEMATICS OCCUPATIONS', 'OPERATIONS RESEARCH'),
 '1520': ('MATHEMATICS OCCUPATIONS', 'MATHEMATICS'),
 '1529': ('MATHEMATICS OCCUPATIONS', 'MATHEMATICAL STATISTICS'),
 '1530': ('MATHEMATICS OCCUPATIONS', 'STATISTICS'),
 '1541': ('MATHEMATICS OCCUPATIONS', 'CRYPTANALYSIS'),
 '1550': ('MATHEMATICS OCCUPATIONS', 'COMPUTER SCIENCE'),
 '1730': ('SCIENCE OCCUPATIONS', 'EDUCATION RESEARCH'),
 '2210': ('TECHNOLOGY OCCUPATIONS', 'INFORMATION TECHNOLOGY MANAGEMENT'),
 '2608': ('ENGINEERING OCCUPATIONS', 'ELECTRONIC DIGITAL COMPUTER MECHANIC'),
 '3314': ('ENGINEERING OCCUPATIONS', 'INSTRUMENT MAKING'),
 '4714': ('ENGINEERING OCCUPATIONS', 'MODEL MAKING'),
 '5205': ('SCIENCE OCCUPATIONS', 'GAS AND RADIATION DETECTING'),
 'XXXX': ('ALL OTHER OCCUPATIONS', 'ALL OTHER OCCUPATIONS')}

In [ ]:

with open('stemocc_dict.json', 'w') as f:
  f.write(json.dumps(stemocc_dict))

In [ ]:
df2['STEMOCC'] = df.apply(lambda row: stemocc_dict[row.STEMOCC][0], axis = 1)
df2['STEMOCCT'] = df.apply(lambda row: stemocc_dict[row.STEMOCC][1], axis = 1)
df2

                     LOC AGELVL  ...  SALARY               STEMOCCT
0   DISTRICT OF COLUMBIA  40-44  ...  181500  ALL OTHER OCCUPATIONS
1   DISTRICT OF COLUMBIA  55-59  ...  181500  ALL OTHER OCCUPATIONS
2   DISTRICT OF COLUMBIA  35-39  ...  172500  ALL OTHER OCCUPATIONS
3   DISTRICT OF COLUMBIA  30-34  ...  144128  ALL OTHER OCCUPATIONS
4   DISTRICT OF COLUMBIA  40-44  ...  114059  ALL OTHER OCCUPATIONS
5   DISTRICT OF COLUMBIA  50-54  ...  199300  ALL OTHER OCCUPATIONS
6   DISTRICT OF COLUMBIA  35-39  ...  134782  ALL OTHER OCCUPATIONS
7   DISTRICT OF COLUMBIA  30-34  ...  126614  ALL OTHER OCCUPATIONS
8   DISTRICT OF COLUMBIA  35-39  ...  138866  ALL OTHER OCCUPATIONS
9                 FRANCE  55-59  ...   87415  ALL OTHER OCCUPATIONS
10                FRANCE  55-59  ...   87415              CHEMISTRY

[11 rows x 10 columns]

In [ ]:
# 479 4,Small Independent Agencies (less than 100 employees),AA,AA-ADMINISTRATIVE CONFERENCE OF THE UNITED STATES,AA00,AA00-ADMINISTRATIVE CONFERENCE OF THE UNITED STATES

In [ ]:
# 1,United States,11,11-DISTRICT OF COLUMBIA

In [ ]:
# F,40-44

In [ ]:
# 5,BACHELORS,13,13-BACHELOR'S DEGREE

In [ ]:
# GSEGRD: -

In [ ]:
# F,15 - 19 years

In [ ]:
# 1,White Collar,03,"03xx-GENERAL ADMIN, CLERICAL, & OFFICE SVCS",0340,0340-PROGRAM MANAGEMENT

In [ ]:
# 2,Administrative

In [ ]:
# 1,SES/SL/ST (Aggregate),ES,ES-Senior Executive Service (SES)

In [ ]:
# 3,Other White Collar Pay Plans,31,Governmentwide or Multi-Agency Plans,ES,ES-SENIOR EXECUTIVE SERVICE,ES-**

In [ ]:
# 3,ALL OTHER OCCUPATIONS,06,ALL OTHER OCCUPATIONS,XXXX,XXXX-ALL OTHER OCCUPATIONS

## Average salary for white collar employees between age 40-44.

## Salary difference between occupation categories.

## Salary difference based on education level.

## Salary difference based on location.

## Key differences between the richest and the poorest.

## Difference between education and supervisory status.